name: healing_music
description: "HealingMusic.HealingAI.Top"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  get: ^4.6.6
  just_audio: ^0.9.42
  just_waveform: ^0.0.5
  audio_wave: ^0.1.5
  spectrum_lib: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  logging: ^1.3.0
  flutter_dotenv: ^5.2.1
  crypto: ^3.0.6
  permission_handler: ^11.3.1
  http: ^1.2.2
  web_socket_channel: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/json/
    - .env

